<a href="https://colab.research.google.com/github/ckraju/mits/blob/master/marks-spa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving spa.csv to spa.csv


In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score


In [3]:
import io

df2 = pd.read_csv(io.BytesIO(uploaded['spa.csv']))

# Dataset is now stored in a Pandas Dataframe

In [4]:
df2

85  54  63  1  76  5
0    85  66  75  1  71  5
1    85  74  87  1  82  6
2    55  32  67  1  78  5
3    88  76  93  1  82  6
4    90  81  91  1  86  6
..   ..  ..  .. ..  .. ..
922  70  56  54  1   0  1
923  70  70  77  1  78  5
924  60   0  56  1  55  3
925  40   0  45  1   0  1
926  40   0  47  2  42  2

[927 rows x 6 columns]

In [5]:
# fix random seed for reproducibility
seed = 8
numpy.random.seed(seed)
# load pima indians dataset
dataset = numpy.loadtxt("spa.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:4]
Y = dataset[:,5]

In [6]:
X

array([[85., 54., 63.,  1.],
       [85., 66., 75.,  1.],
       [85., 74., 87.,  1.],
       ...,
       [60.,  0., 56.,  1.],
       [40.,  0., 45.,  1.],
       [40.,  0., 47.,  2.]])

In [7]:
Y

array([5., 5., 6., 5., 6., 6., 7., 7., 5., 6., 5., 5., 6., 6., 6., 5., 5.,
       6., 6., 7., 6., 6., 7., 5., 5., 5., 4., 5., 6., 6., 7., 7., 4., 5.,
       6., 6., 6., 5., 1., 5., 6., 5., 5., 6., 5., 5., 7., 6., 5., 6., 6.,
       6., 6., 6., 7., 6., 6., 6., 6., 5., 2., 7., 4., 7., 4., 6., 5., 7.,
       2., 7., 3., 4., 7., 6., 1., 7., 4., 7., 7., 7., 4., 7., 7., 6., 7.,
       5., 7., 5., 7., 4., 5., 6., 7., 6., 6., 7., 6., 1., 6., 4., 3., 6.,
       4., 4., 5., 4., 7., 5., 5., 5., 7., 3., 7., 6., 2., 5., 7., 4., 7.,
       6., 2., 4., 7., 6., 4., 4., 6., 6., 7., 4., 4., 5., 3., 4., 7., 4.,
       5., 5., 4., 1., 3., 3., 3., 4., 1., 7., 7., 3., 6., 7., 5., 3., 7.,
       4., 1., 5., 5., 4., 4., 6., 4., 4., 7., 1., 3., 4., 5., 1., 3., 7.,
       5., 4., 4., 1., 7., 6., 6., 5., 5., 7., 5., 5., 5., 7., 7., 7., 6.,
       5., 7., 7., 5., 7., 5., 5., 5., 7., 5., 7., 7., 6., 5., 5., 7., 7.,
       6., 7., 7., 7., 7., 5., 7., 5., 6., 6., 7., 7., 5., 7., 7., 7., 7.,
       7., 7., 7., 1., 6.

In [8]:
X

array([[85., 54., 63.,  1.],
       [85., 66., 75.,  1.],
       [85., 74., 87.,  1.],
       ...,
       [60.,  0., 56.,  1.],
       [40.,  0., 45.,  1.],
       [40.,  0., 47.,  2.]])

In [9]:
X = (X-X.min())/(X.max()-X.min())

In [10]:
X

array([[0.86111111, 0.57407407, 0.65740741, 0.08333333],
       [0.86111111, 0.68518519, 0.76851852, 0.08333333],
       [0.86111111, 0.75925926, 0.87962963, 0.08333333],
       ...,
       [0.62962963, 0.07407407, 0.59259259, 0.08333333],
       [0.44444444, 0.07407407, 0.49074074, 0.08333333],
       [0.44444444, 0.07407407, 0.50925926, 0.09259259]])

In [11]:
Y

array([5., 5., 6., 5., 6., 6., 7., 7., 5., 6., 5., 5., 6., 6., 6., 5., 5.,
       6., 6., 7., 6., 6., 7., 5., 5., 5., 4., 5., 6., 6., 7., 7., 4., 5.,
       6., 6., 6., 5., 1., 5., 6., 5., 5., 6., 5., 5., 7., 6., 5., 6., 6.,
       6., 6., 6., 7., 6., 6., 6., 6., 5., 2., 7., 4., 7., 4., 6., 5., 7.,
       2., 7., 3., 4., 7., 6., 1., 7., 4., 7., 7., 7., 4., 7., 7., 6., 7.,
       5., 7., 5., 7., 4., 5., 6., 7., 6., 6., 7., 6., 1., 6., 4., 3., 6.,
       4., 4., 5., 4., 7., 5., 5., 5., 7., 3., 7., 6., 2., 5., 7., 4., 7.,
       6., 2., 4., 7., 6., 4., 4., 6., 6., 7., 4., 4., 5., 3., 4., 7., 4.,
       5., 5., 4., 1., 3., 3., 3., 4., 1., 7., 7., 3., 6., 7., 5., 3., 7.,
       4., 1., 5., 5., 4., 4., 6., 4., 4., 7., 1., 3., 4., 5., 1., 3., 7.,
       5., 4., 4., 1., 7., 6., 6., 5., 5., 7., 5., 5., 5., 7., 7., 7., 6.,
       5., 7., 7., 5., 7., 5., 5., 5., 7., 5., 7., 7., 6., 5., 5., 7., 7.,
       6., 7., 7., 7., 7., 5., 7., 5., 6., 6., 7., 7., 5., 7., 7., 7., 7.,
       7., 7., 7., 1., 6.

In [12]:
# Split the data into training/testing sets
diabetes_X_train = X[:-20]
diabetes_X_test = X[-20:]

# Split the targets into training/testing sets
diabetes_y_train = Y[:-20]
diabetes_y_test = Y[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the training set
diabetes_y_pred = regr.predict(diabetes_X_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)
# Use score method to get accuracy of model
score = regr.score(diabetes_X_test, diabetes_y_test)
print(score)

0.9189931483912768
